/**
 * Variáveis estáticas.
 *
 * */
var SEPARA_ROLE = "|:";
var PREFIXO_ROLE = "Alo_";

var RESOURCE_BUNDLE = 'RESOURCE_BUNDLE';

var COMBO_GERENTE_CUSTOS = 'COMBO_GERENTE_CUSTOS';
var COMBO_GERENTE_OBRA = 'COMBO_GERENTE_OBRA';
var COMBO_UNIDADE_MEDIDA = 'COMBO_UNIDADE_MEDIDA';
var COMBO_PRIORIDADES = 'COMBO_PRIORIDADES';
var COMBO_TIPO_REQUISICAO = 'COMBO_TIPO_REQUISICAO';
var COMBO_TIPO_REQUISICAO_USUARIO = 'COMBO_TIPO_REQUISICAO_USUARIO';
var COMBO_TIPO_REQUISICAO_COM_FRENTE_SERVICO = 'COMBO_TIPO_REQUISICAO_COM_FRENTE_SERVICO';
var COMBO_DEPOSITOS = 'COMBO_DEPOSITOS';
var COMBO_DEPOSITOS_TEMPORARIOS = 'COMBO_DEPOSITOS_TEMPORARIOS';
var COMBO_STATUS = 'COMBO_STATUS';
var COMBO_COMPRADOR = 'COMBO_COMPRADOR';
var COMBO_EQUIPE_CUSTOS = 'COMBO_EQUIPE_CUSTOS';
var COMBO_LIDER_CUSTOS = 'COMBO_LIDER_CUSTOS';
var COMBO_COORDENADOR = 'COMBO_COORDENADOR';
var COMBO_EAP_MULTI_EMPRESA = 'COMBO_EAP_MULTI_EMPRESA';

var ROLE_REQUISITANTE = "ROLE_REQUISITANTE";
var ROLE_REQUISITANTE_CORPORATIVO = "ROLE_REQUISITANTE_CORPORATIVO";
var ROLE_CADASTRAR_CONSULTAR = "ROLE_CADASTRAR_CONSULTAR";
var ROLE_APROVAR = "ROLE_APROVAR";
var ROLE_ADMINISTRAR_ENVIO_SAP = "ROLE_ADMINISTRAR_ENVIO_SAP";
var ROLE_RASTREABILIDADE = "ROLE_RASTREABILIDADE";
var ROLE_SUPRIMENTOS = "ROLE_SUPRIMENTOS";
var ROLE_PAINEL_REQUISICAO_MATERIAIS = "ROLE_PAINEL_REQUISICAO_MATERIAIS";
var ROLE_MATERIAIS_SEM_CODIGO_SAP = "ROLE_MATERIAIS_SEM_CODIGO_SAP";
var ROLE_DOCUMENTO_RESPONSABILIDADE = "ROLE_DOCUMENTO_RESPONSABILIDADE";
var ROLE_GESTAO_ESTOQUE = "ROLE_GESTAO_ESTOQUE";
var ROLE_RELATORIO_GESTAO = "ROLE_RELATORIO_GESTAO";
var ROLE_RELATORIO_PREVISOES_PENDENCIA_RECEBIMENTO = "ROLE_RELATORIO_PREVISOES_PENDENCIA_RECEBIMENTO";
var ROLE_LOG_INTERFACE = "ROLE_LOG_INTERFACE";
var ROLE_HIERARQUIA_COMPRADOR = "ROLE_HIERARQUIA_COMPRADOR";
var ROLE_USUARIOS = "ROLE_USUARIOS";
var ROLE_PERFIL = "ROLE_PERFIL";
var ROLE_CADASTRO_OBRA = "ROLE_CADASTRO_OBRA";
var ROLE_USUARIOS_CADASTRO = "ROLE_USUARIOS_CADASTRO";
var ROLE_ADMINISTRADOR = "ROLE_ADMINISTRADOR";
var ROLE_WORKFLOW = "ROLE_WORKFLOW";
var ROLE_COMPRADOR = "ROLE_COMPRADOR";
var ROLE_ALMOXARIFE = "ROLE_ALMOXARIFE";
var ROLE_ALTERAR_MATERIAL = "ROLE_ALTERAR_MATERIAL";
var ROLE_MOVIMENTACAO_ESTOQUE = "ROLE_MOVIMENTACAO_ESTOQUE";

var DIAGRAMA_DE_REDE = "DIAGRAMA_DE_REDE";
var OPERACAO_PEP = "OPERACAO_PEP";
var ORDEM = "ORDEM";
var ESTOQUE = "ESTOQUE";

var TODOS = "TODOS";

var TIPO_APROVADOR_GERENTE_CUSTO = "GC";
var TIPO_APROVADOR_GERENTE_AREA = "GA";
var TIPO_APROVADOR_GERENTE_OBRA = "GO";
var TIPO_APROVADOR_CUSTOS = "C";
var TIPO_APROVADOR_LIDER_CUSTOS = "LC";
var TIPO_APROVADOR_COORDENADOR = "CO";
var TIPO_APROVADOR_RESP_RET_ESTOQ = "RRE";

var TIPO_PENDENCIA_TODAS = "";
var TIPO_PENDENCIA_ATRASADAS = "ATR";
var TIPO_PENDENCIA_DENTRO_PRAZO = "NPR";

var TIPO_PRIORIDADE_ALTA = "ALTA";

var STATE_TRANSFERENCIA = "STATE_TRANSFERENCIA";

var TIPO_REQUISICAO_FRENTE_SERVICO = "TIP_REQ_FRE_SER";
var TIPO_REQUISICAO_MANUTENCAO = "TIP_REQ_MANUTENCAO";
var TIPO_REQUISICAO_RESP_ESTOQ = "TIP_RET_EM_ESTOQ";
var TIPO_REQUISICAO_RET_ESTOQUISTA = "TIP_RET_ESTOQUISTA";
var TIP_REQ_MAT = "TIP_REQ_MAT";

var INTEGRACAO_COMPRA_MATERIAL = "INTEGRACAO_COMPRA_MATERIAL";
var INTEGRACAO_RETIRADA_MATERIAL = "INTEGRACAO_RETIRADA_MATERIAL";

var SINC_EQUIPAMENTO = "SincEquipamento";
var SINC_TRANF_EQUIPAMENTO = "SincTransfEquipamento";
var SINC_GERA_CAUTELA = "SincGeraCautela";
var SINC_RESERVA = "SincReserva";

var SISTEMA_RMA_WEB = "RMAWEB";
var SISTEMA_CP_WEB = "CPWEB";
var SISTEMA_SAP = "SAP";
var TP_SOL_SPOT = "Serviço PONTUAL (SPOT)";
var TP_SOL_CONTRATO = "Serviço CONTRATO";
var TP_SOL_CONTRATO = "Serviço SUBEMPREITADA";